version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'MediaStoragePg'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=MediaStorageDb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin